jobs:
    build:
        runs-on: ...
        steps:
            - uses: actions/checkout@v3

            # ... some other preparation steps (dependencies, compilation as a separate step, etc) ...

            - name: Setup Testcontainers Cloud Client
              uses: atomicjar/testcontainers-cloud-setup-action@v1
              with:
                  token: ${{ secrets.TC_CLOUD_TOKEN }}
            - name: Docker Scout
              uses: docker/scout-action@v1.20.4

            - name: Build and push Docker images
              uses: docker/build-push-action@v7.1.0

            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v4.0.0

            - name: Docker Login
              uses: docker/login-action@v4.1.0

            # ... existing steps executing your Testcontainers tests go here ...